SELECT
    (SUM(CASE WHEN t.AMOUNT > 0 THEN t.AMOUNT ELSE 0 END) >
     SUM(CASE WHEN t.AMOUNT < 0 THEN ABS(t.AMOUNT) ELSE 0 END))
FROM PRODUCTS p
         JOIN TRANSACTIONS t ON p.ID = t.PRODUCT_ID
WHERE p.TYPE = 'DEBIT'
  AND t.USER_ID = ?