SELECT
    (SUM(CASE WHEN p.TYPE = 'DEBIT' THEN t.AMOUNT ELSE 0 END) >= 50000) AS debit_condition,
    (SUM(CASE WHEN p.TYPE = 'SAVING' THEN t.AMOUNT ELSE 0 END) >= 50000) AS saving_condition
FROM PRODUCTS p
         JOIN TRANSACTIONS t ON p.ID = t.PRODUCT_ID
WHERE t.AMOUNT > 0
  AND t.USER_ID = ?